#!/usr/bin/env python

import sys
import numpy as np
import cv2
import os
from pylepton.Lepton3 import Lepton3

def capture(flip_v = False, device = "/dev/spidev0.0"):
  with Lepton3(device) as l:
    a,_ = l.capture()
  if flip_v:
    cv2.flip(a,0,a)
  cv2.normalize(a, a, 0, 65535, cv2.NORM_MINMAX)
  np.right_shift(a, 8, a)
  return np.uint8(a)

if __name__ == '__main__':
  from optparse import OptionParser

  usage = "usage: %prog [options] output_file[.format]"
  parser = OptionParser(usage=usage)

  parser.add_option("-f", "--flip-vertical",
                    action="store_true", dest="flip_v", default=False,
                    help="flip the output image vertically")

  parser.add_option("-d", "--device",
                    dest="device", default="/dev/spidev0.0",
                    help="specify the spi device node (might be /dev/spidev0.1 on a newer device)")

  (options, args) = parser.parse_args()

  if len(args) < 1:
    print("You must specify an output filename")
    sys.exit(1)

  image = capture(flip_v = options.flip_v, device = options.device)
  cv2.imwrite(args[0], image)
  
  cmd="convert /home/pi/test2/pylepton/" +(args[0]) + " -compress None asc"+(args[0])
  os.system(cmd)    
  
  
  
  #grey_img = cv2.imread (args[0], cv2.IMREAD_GRAYSCALE)
  #cv2.imwrite(args[0],grey_img)
  
 
  #fil_e= (args[0])
  #print (fil_e)
  #cmd='convert "(fil_e)" -compress None 0.pgm'
  #os.system(cmd)    
  
  #img = cv2.imread(args[0],0)
  #cv2.imshow('image',img)
  #k = cv2.waitKey(0)
  #if k == 27:         # wait for ESC key to exit
  #  cv2.destroyAllWindows()
  #elif k == ord('s'): # wait for 's' key to save and exit
  #  cv2.imwrite('messigray.png',img)
  #  cv2.destroyAllWindows()

  
  
  
  
  
